steps:
    #step 1
    - name: 'gcr.io/cloud-builders/docker' 
      entrypoint: 'bash'
      args: [
       '-c', 
       'docker pull gcr.io/$PROJECT_ID/circleci:latest || exit 0'
      ]
    #step 2
    - name: gcr.io/cloud-builders/docker
      args: [
       'build', 
       '-t', 
       'gcr.io/$PROJECT_ID/circleci:$TAG_NAME',
       '-t', 
       'gcr.io/$PROJECT_ID/circleci:latest',
       '.'
      ]
    #step 3
    - name: 'gcr.io/cloud-builders/kubectl'
      args: ['apply', '-f', 'k8s/']
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=circle-ci-cluster'
    #step 4
    - name: 'gcr.io/cloud-builders/kubectl'
      args: [
       'set', 
       'image', 
       'deployment', 
       'circleci', 
       'circleci=gcr.io/$PROJECT_ID/circleci:$TAG_NAME'
      ]
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=circle-ci-cluster'
    # push images to Google Container Registry with tags
    images: [
       'gcr.io/$PROJECT_ID/circleci:$TAG_NAME',
       'gcr.io/$PROJECT_ID/circleci:latest'
      ]